const express=require('express');const session=require('express-session');const {Pool}=require('pg');const bcrypt=require('bcryptjs');const path=require('path');const app=express();
app.use(express.json({limit:'4mb'}));app.use(express.urlencoded({extended:true,limit:'4mb'}));
app.use(session({secret:process.env.SESSION_SECRET||'change-this-session-secret',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production'}}));
app.use(express.static(path.join(__dirname,'public')));
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?{rejectUnauthorized:false}:false});let dbReady=false;
async function init(){if(!process.env.DATABASE_URL)throw Error('DATABASE_URL is not configured');await pool.query(`CREATE TABLE IF NOT EXISTS members(id SERIAL PRIMARY KEY,member_id VARCHAR(30) UNIQUE NOT NULL,full_name TEXT NOT NULL,phone VARCHAR(40),email TEXT,state TEXT,lga TEXT,gender VARCHAR(30),date_of_birth DATE,address TEXT,emergency_contact TEXT,emergency_phone VARCHAR(40),blood_group VARCHAR(10),qualification TEXT,first_aid_level TEXT,unit TEXT,year_of_entry VARCHAR(10),rank TEXT,office_description TEXT,photo_url TEXT,status VARCHAR(20) DEFAULT 'pending',created_at TIMESTAMPTZ DEFAULT NOW(),approved_at TIMESTAMPTZ);CREATE TABLE IF NOT EXISTS admins(id SERIAL PRIMARY KEY,username VARCHAR(80) UNIQUE NOT NULL,password_hash TEXT NOT NULL,role VARCHAR(30) DEFAULT 'approver',created_at TIMESTAMPTZ DEFAULT NOW());`);const {rows}=await pool.query('SELECT COUNT(*)::int n FROM admins');if(rows[0].n===0){const hash=await bcrypt.hash(process.env.ADMIN_PASSWORD||'FityanulAdmin2026!',12);await pool.query('INSERT INTO admins(username,password_hash,role) VALUES($1,$2,$3)',[process.env.ADMIN_USERNAME||'admin',hash,'super_admin']);}dbReady=true;console.log('Database ready')}
init().catch(e=>console.error('Database initialization pending:',e.message));
const db=(req,res,next)=>dbReady?next():res.status(503).json({error:'Database is still connecting. Please try again shortly.'});
const admin=(req,res,next)=>req.session.admin?next():res.status(401).json({error:'Admin login required'});
function newId(){return'FNI-'+Date.now().toString(36).toUpperCase()+'-'+Math.random().toString(36).slice(2,6).toUpperCase()}
app.get('/api/health',(req,res)=>res.json({ok:true,database:dbReady}));
app.post('/api/register',db,async(req,res)=>{try{const d=req.body;if(!d.full_name)return res.status(400).json({error:'Full name is required'});const id=newId();await pool.query(`INSERT INTO members(member_id,full_name,phone,email,state,lga,gender,date_of_birth,address,emergency_contact,emergency_phone,blood_group,qualification,first_aid_level,unit,year_of_entry,photo_url) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17)`,[id,d.full_name,d.phone,d.email,d.state,d.lga,d.gender,d.date_of_birth||null,d.address,d.emergency_contact,d.emergency_phone,d.blood_group,d.qualification,d.first_aid_level,d.unit,d.year_of_entry,d.photo_url]);res.json({ok:true,member_id:id})}catch(e){console.error(e);res.status(500).json({error:'Unable to submit registration'})}});
app.get('/api/member/:id',db,async(req,res)=>{try{const {rows}=await pool.query('SELECT * FROM members WHERE member_id=$1 AND status=$2',[req.params.id,'approved']);if(!rows[0])return res.status(404).json({error:'Approved member not found'});res.json(rows[0])}catch(e){res.status(500).json({error:'Search failed'})}});
app.post('/api/admin/login',db,async(req,res)=>{try{const {username,password}=req.body,{rows}=await pool.query('SELECT * FROM admins WHERE username=$1',[username]);if(!rows[0]||!(await bcrypt.compare(password,rows[0].password_hash)))return res.status(401).json({error:'Invalid username or password'});req.session.admin={id:rows[0].id,username:rows[0].username,role:rows[0].role};res.json({ok:true,admin:req.session.admin})}catch(e){res.status(500).json({error:'Login failed'})}});
app.post('/api/admin/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true})));app.get('/api/admin/me',admin,(req,res)=>res.json(req.session.admin));
app.get('/api/admin/stats',admin,db,async(req,res)=>{try{const {rows}=await pool.query(`SELECT COUNT(*)::int AS total,COUNT(*) FILTER(WHERE status='pending')::int AS pending,COUNT(*) FILTER(WHERE status='approved')::int AS approved,COUNT(*) FILTER(WHERE status='rejected')::int AS rejected,COUNT(*) FILTER(WHERE photo_url IS NOT NULL AND photo_url<>'')::int AS with_photo FROM members`);const units=await pool.query(`SELECT COALESCE(NULLIF(unit,''),'Unassigned') unit,COUNT(*)::int count FROM members GROUP BY 1 ORDER BY count DESC,unit`);res.json({summary:rows[0],units:units.rows})}catch(e){res.status(500).json({error:'Unable to load statistics'})}});
app.get('/api/admin/members',admin,db,async(req,res)=>{try{const s=req.query.status||'all',q=(req.query.q||'').trim();const params=[];const where=[];if(s!=='all'){params.push(s);where.push(`status=$${params.length}`)}if(q){params.push('%'+q+'%');where.push(`(full_name ILIKE $${params.length} OR member_id ILIKE $${params.length} OR phone ILIKE $${params.length} OR unit ILIKE $${params.length})`)}const sql=`SELECT * FROM members ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY created_at DESC`;const {rows}=await pool.query(sql,params);res.json(rows)}catch(e){res.status(500).json({error:'Unable to load members'})}});
app.get('/api/admin/members/:id',admin,db,async(req,res)=>{try{const {rows}=await pool.query('SELECT * FROM members WHERE id=$1',[req.params.id]);if(!rows[0])return res.status(404).json({error:'Member not found'});res.json(rows[0])}catch(e){res.status(500).json({error:'Unable to load member'})}});
app.patch('/api/admin/members/:id',admin,db,async(req,res)=>{try{const d=req.body;const allowed=['approved','rejected','pending'];if(d.status&&!allowed.includes(d.status))return res.status(400).json({error:'Invalid status'});const {rows}=await pool.query(`UPDATE members SET full_name=COALESCE($1,full_name),phone=COALESCE($2,phone),email=COALESCE($3,email),state=COALESCE($4,state),lga=COALESCE($5,lga),gender=COALESCE($6,gender),date_of_birth=COALESCE($7,date_of_birth),address=COALESCE($8,address),emergency_contact=COALESCE($9,emergency_contact),emergency_phone=COALESCE($10,emergency_phone),blood_group=COALESCE($11,blood_group),qualification=COALESCE($12,qualification),first_aid_level=COALESCE($13,first_aid_level),unit=COALESCE($14,unit),year_of_entry=COALESCE($15,year_of_entry),rank=COALESCE($16,rank),office_description=COALESCE($17,office_description),photo_url=COALESCE($18,photo_url),status=COALESCE($19,status),approved_at=CASE WHEN COALESCE($19,status)='approved' THEN COALESCE(approved_at,NOW()) ELSE approved_at END WHERE id=$20 RETURNING *`,[d.full_name,d.phone,d.email,d.state,d.lga,d.gender,d.date_of_birth||null,d.address,d.emergency_contact,d.emergency_phone,d.blood_group,d.qualification,d.first_aid_level,d.unit,d.year_of_entry,d.rank,d.office_description,d.photo_url,d.status,req.params.id]);if(!rows[0])return res.status(404).json({error:'Member not found'});res.json(rows[0])}catch(e){console.error(e);res.status(500).json({error:'Update failed'})}});
app.post('/api/admin/members/:id/photo',admin,db,async(req,res)=>{try{if(!req.body.photo_url)return res.status(400).json({error:'Photo is required'});const {rows}=await pool.query('UPDATE members SET photo_url=$1 WHERE id=$2 RETURNING *',[req.body.photo_url,req.params.id]);if(!rows[0])return res.status(404).json({error:'Member not found'});res.json(rows[0])}catch(e){res.status(500).json({error:'Photo update failed'})}});
app.delete('/api/admin/members/:id',admin,db,async(req,res)=>{try{if(req.session.admin.role!=='super_admin')return res.status(403).json({error:'Super admin only'});const r=await pool.query('DELETE FROM members WHERE id=$1',[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Member not found'});res.json({ok:true})}catch(e){res.status(500).json({error:'Delete failed'})}});
app.get('/api/admin/admins',admin,db,async(req,res)=>{try{if(req.session.admin.role!=='super_admin')return res.status(403).json({error:'Super admin only'});const {rows}=await pool.query('SELECT id,username,role,created_at FROM admins ORDER BY created_at');res.json(rows)}catch(e){res.status(500).json({error:'Unable to load admins'})}});
app.post('/api/admin/admins',admin,db,async(req,res)=>{try{if(req.session.admin.role!=='super_admin')return res.status(403).json({error:'Super admin only'});const {username,password,role='approver'}=req.body;if(!username||!password)return res.status(400).json({error:'Username and password are required'});const hash=await bcrypt.hash(password,12);await pool.query('INSERT INTO admins(username,password_hash,role) VALUES($1,$2,$3)',[username,password,role].map((x,i)=>i===1?hash:x));res.json({ok:true})}catch(e){res.status(400).json({error:'Could not create admin'})}});
const PORT=process.env.PORT||10000;app.listen(PORT,()=>console.log('Fityanul Islam portal running on '+PORT));